import "server-only";
import { Resend } from "resend";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

let _client: Resend | null = null;

function getClient(): Resend | null {
  if (_client) return _client;
  const key = process.env.RESEND_API_KEY;
  if (!key) return null;
  _client = new Resend(key);
  return _client;
}

export function isEmailConfigured(): boolean {
  return Boolean(process.env.RESEND_API_KEY);
}

// ---------------------------------------------------------------------------
// Default sender — used when org has no verified custom email
// ---------------------------------------------------------------------------

const DEFAULT_FROM_EMAIL =
  process.env.EMAIL_FROM ?? "noreply@sollos3.com";
const DEFAULT_FROM_NAME =
  process.env.EMAIL_FROM_NAME ?? "Sollos";

// ---------------------------------------------------------------------------
// Types — unchanged from the MailerSend implementation so every caller
// (automations.ts, crons, invoice actions, etc.) still works as-is.
// ---------------------------------------------------------------------------

export type SendEmailArgs = {
  /** Recipient address */
  to: string;
  /** Recipient display name (optional, prepended to the address if set) */
  toName?: string;
  /** Email subject */
  subject: string;
  /** HTML body */
  html: string;
  /** Plain text fallback (auto-generated by Resend if omitted, but we pass it for better deliverability) */
  text?: string;
  /** Override the From address (must be on a domain verified in Resend) */
  from?: string;
  /** Override the From display name */
  fromName?: string;
  /** Reply-To address (falls back to from, then default) */
  replyTo?: string;
  /** Reply-To display name */
  replyToName?: string;
};

/**
 * Format an address as Resend expects it. Resend accepts either a bare
 * email or `"Display Name <email@domain.com>"`.
 */
function formatAddress(email: string, name?: string): string {
  if (!name || name === email) return email;
  // Strip any embedded quotes/angles in the name to avoid header injection.
  const safeName = name.replace(/[<>"]/g, "").trim();
  if (!safeName) return email;
  return `${safeName} <${email}>`;
}

// ---------------------------------------------------------------------------
// Send — fire-and-forget safe (never throws, logs errors)
// ---------------------------------------------------------------------------

export async function sendEmail(args: SendEmailArgs): Promise<boolean> {
  const client = getClient();
  if (!client) {
    console.warn("[email] Resend not configured, skipping:", args.subject);
    return false;
  }

  try {
    const fromEmail = args.from ?? DEFAULT_FROM_EMAIL;
    const fromName = args.fromName ?? DEFAULT_FROM_NAME;

    const payload: Parameters<typeof client.emails.send>[0] = {
      from: formatAddress(fromEmail, fromName),
      to: [formatAddress(args.to, args.toName)],
      subject: args.subject,
      html: args.html,
      ...(args.text ? { text: args.text } : {}),
      ...(args.replyTo
        ? { replyTo: formatAddress(args.replyTo, args.replyToName) }
        : {}),
    };

    const { data, error } = await client.emails.send(payload);

    if (error) {
      console.error("[email] send failed:", args.subject, error);
      return false;
    }

    if (!data?.id) {
      console.warn("[email] send returned no id:", args.subject);
      return false;
    }

    return true;
  } catch (err) {
    console.error("[email] send threw:", args.subject, err);
    return false;
  }
}

// ---------------------------------------------------------------------------
// Org-aware sender — reads the org's verified sender email and uses it
// as From if verified, otherwise falls back to default + reply-to
// ---------------------------------------------------------------------------

type OrgSenderInfo = {
  from: string;
  fromName: string;
  replyTo?: string;
  replyToName?: string;
};

export async function getOrgSender(
  organizationId: string,
): Promise<OrgSenderInfo> {
  const admin = createSupabaseAdminClient();
  const { data } = await admin
    .from("organizations")
    .select("name, sender_email, sender_email_verified_at")
    .eq("id", organizationId)
    .maybeSingle();

  const org = data as {
    name: string;
    sender_email: string | null;
    sender_email_verified_at: string | null;
  } | null;

  const isVerified = Boolean(
    org?.sender_email && org?.sender_email_verified_at,
  );

  if (isVerified && org?.sender_email) {
    // Verified custom domain — use as From directly.
    // Resend must also have this domain verified.
    return {
      from: org.sender_email,
      fromName: org.name,
    };
  }

  // Not verified — send from Sollos, but put their email in Reply-To
  // so client replies go to the right place.
  return {
    from: DEFAULT_FROM_EMAIL,
    fromName: DEFAULT_FROM_NAME,
    replyTo: org?.sender_email ?? undefined,
    replyToName: org?.name ?? undefined,
  };
}

// ---------------------------------------------------------------------------
// Platform kill switch for client-facing email
//
// Set CLIENT_EMAILS_PAUSED=true in Vercel env to block EVERY org→client
// email across the whole platform (booking confirm/reschedule, invoice,
// receipt, review request, overdue reminder) without requiring org owners
// to flip their per-org automation toggles. Platform emails that use
// sendEmail() directly (team invite, sender verify, trial expiring) are
// unaffected — those are internal.
//
// To pause: set CLIENT_EMAILS_PAUSED=true in Vercel → Production, redeploy.
// To resume: delete the var (or set it to anything other than "true"),
// redeploy. Pause is ~3 min of latency end-to-end.
// ---------------------------------------------------------------------------

export function isClientEmailPaused(): boolean {
  return process.env.CLIENT_EMAILS_PAUSED === "true";
}

// ---------------------------------------------------------------------------
// Convenience: send an email on behalf of an org
// ---------------------------------------------------------------------------

export async function sendOrgEmail(
  organizationId: string,
  args: Omit<SendEmailArgs, "from" | "fromName" | "replyTo" | "replyToName">,
): Promise<boolean> {
  if (isClientEmailPaused()) {
    console.log(
      `[email] client emails paused at platform level — skipping "${args.subject}" for org ${organizationId}`,
    );
    return false;
  }

  const sender = await getOrgSender(organizationId);
  return sendEmail({
    ...args,
    from: sender.from,
    fromName: sender.fromName,
    replyTo: sender.replyTo,
    replyToName: sender.replyToName,
  });
}
