import "server-only";
import { Resend } from "resend";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { getEnv } from "@/lib/env";

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

let _client: Resend | null = null;

function getClient(): Resend | null {
  if (_client) return _client;
  // Read through the central env system so EMAIL_FROM / EMAIL_FROM_NAME /
  // RESEND_API_KEY are documented and validated in one place (src/lib/env.ts).
  // Set these in Vercel project env vars — see env.ts for the full list.
  const { RESEND_API_KEY } = getEnv();
  if (!RESEND_API_KEY) return null;
  _client = new Resend(RESEND_API_KEY);
  return _client;
}

export function isEmailConfigured(): boolean {
  return Boolean(getEnv().RESEND_API_KEY);
}

// ---------------------------------------------------------------------------
// Default sender — used when org has no verified custom email.
//
// Override via Vercel env vars:
//   EMAIL_FROM      — the "from" address   (default: noreply@sollos3.com)
//   EMAIL_FROM_NAME — the display name     (default: "Sollos")
//
// Both are optional. EMAIL_FROM must be on a domain verified in your Resend
// account or Resend will reject the send with "from_address_not_allowed".
// ---------------------------------------------------------------------------

// Lazy getters so module-level execution doesn't call getEnv() before the
// test/cold-start environment is fully initialised.
function getDefaultFromEmail(): string {
  return getEnv().EMAIL_FROM ?? "noreply@sollos3.com";
}
function getDefaultFromName(): string {
  return getEnv().EMAIL_FROM_NAME ?? "Sollos";
}

// ---------------------------------------------------------------------------
// Types — unchanged from the MailerSend implementation so every caller
// (automations.ts, crons, invoice actions, etc.) still works as-is.
// ---------------------------------------------------------------------------

export type SendEmailArgs = {
  /** Recipient address */
  to: string;
  /** Recipient display name (optional, prepended to the address if set) */
  toName?: string;
  /** Email subject */
  subject: string;
  /** HTML body */
  html: string;
  /** Plain text fallback (auto-generated by Resend if omitted, but we pass it for better deliverability) */
  text?: string;
  /** Override the From address (must be on a domain verified in Resend) */
  from?: string;
  /** Override the From display name */
  fromName?: string;
  /** Reply-To address (falls back to from, then default) */
  replyTo?: string;
  /** Reply-To display name */
  replyToName?: string;
};

/**
 * Format an address as Resend expects it. Resend accepts either a bare
 * email or `"Display Name <email@domain.com>"`.
 */
function formatAddress(email: string, name?: string): string {
  if (!name || name === email) return email;
  // Strip any embedded quotes/angles in the name to avoid header injection.
  const safeName = name.replace(/[<>"]/g, "").trim();
  if (!safeName) return email;
  return `${safeName} <${email}>`;
}

// ---------------------------------------------------------------------------
// Send — fire-and-forget safe (never throws, logs errors)
// ---------------------------------------------------------------------------

/**
 * Rich result for callers that want to surface the actual Resend error
 * (domain not verified, sender not allowed, etc.) to the user instead
 * of showing a generic "delivery failed" message. The legacy
 * sendEmail() wrapper below keeps the boolean return for fire-and-forget
 * callers that don't want to branch.
 */
export type SendEmailResult =
  | { ok: true; id: string }
  | { ok: false; reason: string };

export async function sendEmailDetailed(
  args: SendEmailArgs,
): Promise<SendEmailResult> {
  const client = getClient();
  if (!client) {
    console.warn("[email] Resend not configured, skipping:", args.subject);
    return { ok: false, reason: "Resend not configured (RESEND_API_KEY missing)." };
  }

  try {
    const fromEmail = args.from ?? getDefaultFromEmail();
    const fromName = args.fromName ?? getDefaultFromName();

    const payload: Parameters<typeof client.emails.send>[0] = {
      from: formatAddress(fromEmail, fromName),
      to: [formatAddress(args.to, args.toName)],
      subject: args.subject,
      html: args.html,
      ...(args.text ? { text: args.text } : {}),
      ...(args.replyTo
        ? { replyTo: formatAddress(args.replyTo, args.replyToName) }
        : {}),
    };

    const { data, error } = await client.emails.send(payload);

    if (error) {
      console.error("[email] send failed:", args.subject, error);
      // Resend errors come back as { name, message, statusCode }
      const err = error as { message?: string; name?: string };
      return {
        ok: false,
        reason: err.message ?? err.name ?? "Resend returned an error.",
      };
    }

    if (!data?.id) {
      console.warn("[email] send returned no id:", args.subject);
      return { ok: false, reason: "Resend accepted the request but returned no id." };
    }

    return { ok: true, id: data.id };
  } catch (err) {
    console.error("[email] send threw:", args.subject, err);
    return {
      ok: false,
      reason: err instanceof Error ? err.message : "Unknown send error.",
    };
  }
}

export async function sendEmail(args: SendEmailArgs): Promise<boolean> {
  const r = await sendEmailDetailed(args);
  return r.ok;
}

// ---------------------------------------------------------------------------
// Org-aware sender — reads the org's verified sender email and uses it
// as From if verified, otherwise falls back to default + reply-to
// ---------------------------------------------------------------------------

type OrgSenderInfo = {
  from: string;
  fromName: string;
  replyTo?: string;
  replyToName?: string;
};

/**
 * Domains that are actually verified in our Resend account. Only these
 * can be used as the `from` address — Resend will reject anything else
 * with "from_address_not_allowed". Add a domain here only after DNS
 * verification is complete on the Resend side.
 *
 * Parsed from RESEND_VERIFIED_DOMAINS env var (comma-separated) with
 * sollos3.com as the hardcoded fallback so the platform always has at
 * least one working sender even if the env var is unset.
 */
function getVerifiedDomains(): string[] {
  const raw = process.env.RESEND_VERIFIED_DOMAINS ?? "";
  const envList = raw
    .split(",")
    .map((d) => d.trim().toLowerCase())
    .filter(Boolean);
  if (envList.length > 0) return envList;
  return ["sollos3.com"];
}

function isDomainVerifiedInResend(email: string): boolean {
  const at = email.lastIndexOf("@");
  if (at === -1) return false;
  const domain = email.slice(at + 1).toLowerCase();
  return getVerifiedDomains().includes(domain);
}

/**
 * Resolve the "from" + "reply-to" pair for an org-scoped email.
 *
 * Previously we treated `sender_email_verified_at` (a column we stamp
 * when the user clicks our verify link) as authority to send FROM that
 * address. That's wrong — clicking our link only proves the user owns
 * the inbox. It does NOT mean their domain is verified in Resend, and
 * Resend rejects any `from` on an unverified domain. Net effect: orgs
 * verified their own email, every invoice/booking/receipt email
 * silently bounced.
 *
 * New rule: only send FROM the org's address when its domain is in
 * RESEND_VERIFIED_DOMAINS (or the platform default). Otherwise use the
 * default Sollos `from`, put the org's display name on it ("Velluma
 * via Sollos <noreply@sollos3.com>"), and drop the org's email into
 * Reply-To so client responses land in the owner's inbox.
 */
export async function getOrgSender(
  organizationId: string,
): Promise<OrgSenderInfo> {
  const admin = createSupabaseAdminClient();
  const { data } = await admin
    .from("organizations")
    .select(
      "name, sender_email, sender_email_verified_at, contact_email",
    )
    .eq("id", organizationId)
    .maybeSingle();

  const org = data as {
    name: string;
    sender_email: string | null;
    sender_email_verified_at: string | null;
    contact_email: string | null;
  } | null;

  // Guard: if the org lookup failed (transient DB error, deleted org),
  // log a warning and send as a bare address with no display name.
  // An empty fromName makes formatAddress() return just the raw email
  // address — the client sees "noreply@sollos3.com" instead of the
  // platform brand "Sollos", which would be meaningless to them.
  if (!org) {
    console.warn(
      `[email] getOrgSender: org ${organizationId} not found — sending with no display name`,
    );
    return {
      from: getDefaultFromEmail(),
      fromName: "",
    };
  }

  const canSendFromOrgAddress = Boolean(
    org.sender_email &&
      org.sender_email_verified_at &&
      isDomainVerifiedInResend(org.sender_email),
  );

  // Prefer contact_email as the Reply-To target — it's what the owner
  // explicitly designated for client replies. Fall back to the
  // (possibly unverified) sender_email if they only filled that in.
  const replyTarget = org.contact_email ?? org.sender_email ?? undefined;

  if (canSendFromOrgAddress && org.sender_email) {
    // Owner verified the inbox AND the domain is in our Resend
    // allow-list — safe to send as-them. Still route replies via
    // Reply-To when contact_email differs, so support-style inboxes
    // get the reply even when the From is a noreply@.
    return {
      from: org.sender_email,
      fromName: org.name,
      replyTo:
        org.contact_email && org.contact_email !== org.sender_email
          ? org.contact_email
          : undefined,
      replyToName: org.name,
    };
  }

  // Default path: send from Sollos's verified domain, but stamp the
  // org's display name on the From header so the client sees
  // "Acme Cleaning <noreply@sollos3.com>" — the platform brand
  // stays out of the prominent display slot in Gmail / Outlook.
  // Reply-To carries the org's actual contact inbox.
  return {
    from: getDefaultFromEmail(),
    fromName: org.name,
    replyTo: replyTarget,
    replyToName: org.name,
  };
}

// ---------------------------------------------------------------------------
// Platform kill switch for client-facing email
//
// Set CLIENT_EMAILS_PAUSED=true in Vercel env to block EVERY org→client
// email across the whole platform (booking confirm/reschedule, invoice,
// receipt, review request, overdue reminder) without requiring org owners
// to flip their per-org automation toggles. Platform emails that use
// sendEmail() directly (team invite, sender verify, trial expiring) are
// unaffected — those are internal.
//
// To pause: set CLIENT_EMAILS_PAUSED=true in Vercel → Production, redeploy.
// To resume: delete the var (or set it to anything other than "true"),
// redeploy. Pause is ~3 min of latency end-to-end.
// ---------------------------------------------------------------------------

export function isClientEmailPaused(): boolean {
  return process.env.CLIENT_EMAILS_PAUSED === "true";
}

// ---------------------------------------------------------------------------
// Convenience: send an email on behalf of an org
// ---------------------------------------------------------------------------

export async function sendOrgEmail(
  organizationId: string,
  args: Omit<SendEmailArgs, "from" | "fromName" | "replyTo" | "replyToName">,
): Promise<boolean> {
  const r = await sendOrgEmailDetailed(organizationId, args);
  return r.ok;
}

/**
 * Detailed variant for callers that want to surface the exact reason
 * a send failed (which domain wasn't verified, which sender was
 * rejected, etc.). Use this when you're about to show an inline error
 * to the user — the plain boolean is fine for fire-and-forget paths.
 */
export async function sendOrgEmailDetailed(
  organizationId: string,
  args: Omit<SendEmailArgs, "from" | "fromName" | "replyTo" | "replyToName">,
): Promise<SendEmailResult> {
  if (isClientEmailPaused()) {
    console.log(
      `[email] client emails paused at platform level — skipping "${args.subject}" for org ${organizationId}`,
    );
    return { ok: false, reason: "Client-facing emails are paused at the platform level (CLIENT_EMAILS_PAUSED=true)." };
  }

  const sender = await getOrgSender(organizationId);
  return sendEmailDetailed({
    ...args,
    from: sender.from,
    fromName: sender.fromName,
    replyTo: sender.replyTo,
    replyToName: sender.replyToName,
  });
}
