import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { checkIpRateLimit } from "@/lib/rate-limit-helpers";
import { RateLimitedPage } from "@/components/rate-limited-page";
import { ReviewForm } from "./review-form";

export const metadata: Metadata = {
  title: "Leave a Review",
  description: "Tell us how we did.",
  robots: { index: false, follow: false },
};

/**
 * Public review page — no login required.
 *
 * Accepts two token sources:
 *   1. bookings.review_token  — generated by the 24h post-completion cron
 *      and linked from the client portal jobs page.
 *   2. invoices.review_token  — generated on invoice paid (legacy / parallel
 *      path; clients who receive an invoice still get this one).
 *
 * Resolution order: try booking first, then invoice. The same star-rating
 * form renders in both cases. After a ≥4 star submission the page shows a
 * "Share on Google" CTA using the org's configured google_review_url.
 */
export default async function PublicReviewPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  if (!token || token.length < 8) notFound();

  const rl = await checkIpRateLimit("review-token", 30, 60_000);
  if (!rl.allowed) {
    return <RateLimitedPage retryAfterSeconds={rl.retryAfterSeconds} />;
  }

  const admin = createSupabaseAdminClient();

  // ── Resolution: booking token (new path) ──────────────────────────────────
  type BookingRow = {
    id: string;
    organization_id: string;
    client_id: string | null;
    assigned_to: string | null;
    organization: { id: string; name: string } | null;
    client: { name: string } | null;
  };

  const { data: bookingMatch } = (await admin
    .from("bookings")
    .select(`
      id, organization_id, client_id, assigned_to,
      organization:organizations ( id, name ),
      client:clients ( name )
    `)
    .eq("review_token" as never, token as never)
    .maybeSingle()) as unknown as { data: BookingRow | null };

  // ── Resolution: invoice token (legacy / parallel path) ───────────────────
  type InvoiceRow = {
    id: string;
    organization_id: string;
    client_id: string | null;
    booking_id: string | null;
    organization: { id: string; name: string } | null;
    client: { name: string } | null;
  };

  let invoiceMatch: InvoiceRow | null = null;
  if (!bookingMatch) {
    const { data: invRow } = (await admin
      .from("invoices")
      .select(`
        id, organization_id, client_id, booking_id,
        organization:organizations ( id, name ),
        client:clients ( name )
      `)
      .eq("review_token" as never, token as never)
      .maybeSingle()) as unknown as { data: InvoiceRow | null };
    invoiceMatch = invRow;
  }

  if (!bookingMatch && !invoiceMatch) notFound();

  // ── Common fields ─────────────────────────────────────────────────────────
  const orgId = (bookingMatch ?? invoiceMatch)!.organization_id;
  const clientId = (bookingMatch ?? invoiceMatch)!.client_id;
  const orgName =
    (bookingMatch ?? invoiceMatch)!.organization?.name ?? "our team";
  const clientName =
    (bookingMatch ?? invoiceMatch)!.client?.name ?? null;

  // source/sourceId routed into the form so the action knows which table
  // to verify the token against.
  const source: "booking" | "invoice" = bookingMatch ? "booking" : "invoice";
  const sourceId = bookingMatch ? bookingMatch.id : invoiceMatch!.id;

  // ── Branding + Google Review URL ──────────────────────────────────────────
  const { data: orgData } = (await admin
    .from("organizations")
    .select("logo_url, brand_color, google_review_url")
    .eq("id", orgId)
    .maybeSingle()) as unknown as {
    data: {
      logo_url: string | null;
      brand_color: string | null;
      google_review_url: string | null;
    } | null;
  };

  const logoUrl = orgData?.logo_url ?? null;
  const brandColor = orgData?.brand_color
    ? `#${orgData.brand_color}`
    : "#6366f1";
  const googleReviewUrl = orgData?.google_review_url ?? null;

  // ── Existing review check ─────────────────────────────────────────────────
  // Dedup is per-client per-org — regardless of which token path they arrived
  // via, a client only reviews once.
  const { data: existingReview } = await admin
    .from("reviews")
    .select("id, rating, comment")
    .eq("organization_id", orgId)
    .eq("client_id", clientId ?? "")
    .maybeSingle();

  return (
    <main className="sollos-wash relative flex flex-1 justify-center px-4 py-10">
      <div className="sollos-dots absolute inset-0" aria-hidden />
      <div className="relative z-10 w-full max-w-lg">
        {/* Brand header */}
        <div className="mx-auto mb-6 flex w-max items-center gap-2">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={logoUrl || "/sollos-logo.png"}
            alt={orgName}
            className="h-8 w-8 shrink-0 rounded-lg object-contain"
          />
          <span className="text-base font-semibold tracking-tight">
            {orgName}
          </span>
        </div>

        <div className="sollos-card p-6 shadow-lg shadow-indigo-500/5 sm:p-8">
          {existingReview ? (
            <div className="text-center">
              <div className="mx-auto mb-3 flex w-max gap-1">
                {[1, 2, 3, 4, 5].map((s) => (
                  <span
                    key={s}
                    className={`text-2xl ${s <= existingReview.rating ? "text-amber-400" : "text-muted-foreground/20"}`}
                  >
                    ★
                  </span>
                ))}
              </div>
              <h1 className="text-xl font-bold">Thank you for your review!</h1>
              <p className="mt-2 text-sm text-muted-foreground">
                Your feedback helps {orgName} provide better service.
              </p>
              {existingReview.comment && (
                <blockquote className="mt-4 rounded-md border border-border bg-muted/20 px-4 py-3 text-sm italic text-muted-foreground">
                  &ldquo;{existingReview.comment}&rdquo;
                </blockquote>
              )}
              {/* Even after already reviewing, surface the Google link so
                  they can still post publicly if they haven't yet. */}
              {existingReview.rating >= 4 && googleReviewUrl && (
                <div className="mt-5">
                  <a
                    href={googleReviewUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1.5 rounded-md border border-border bg-background px-3 py-1.5 text-sm font-medium hover:bg-muted"
                  >
                    <GoogleIcon />
                    Share on Google too
                  </a>
                </div>
              )}
            </div>
          ) : (
            <>
              <div className="text-center">
                <h1 className="text-xl font-bold">How did we do?</h1>
                <p className="mt-1 text-sm text-muted-foreground">
                  Thanks for choosing {orgName}! We&apos;d love your feedback.
                </p>
              </div>

              <ReviewForm
                token={token}
                source={source}
                sourceId={sourceId}
                orgName={orgName}
                brandColor={brandColor}
                clientName={clientName}
                googleReviewUrl={googleReviewUrl}
              />
            </>
          )}
        </div>

        <p className="mt-6 text-center text-[11px] text-muted-foreground">
          Your review helps {orgName} improve their service.
        </p>
      </div>
    </main>
  );
}

/** Inline Google "G" icon — avoids an external image fetch on a public page. */
function GoogleIcon() {
  return (
    <svg
      aria-hidden
      viewBox="0 0 24 24"
      className="h-4 w-4"
      fill="none"
    >
      <path
        d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
        fill="#4285F4"
      />
      <path
        d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
        fill="#34A853"
      />
      <path
        d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z"
        fill="#FBBC05"
      />
      <path
        d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
        fill="#EA4335"
      />
    </svg>
  );
}
