-- =============================================================================
-- Phase 12 — Invoicing integrations foundation
--
-- Adds the DB plumbing for a real invoicing flow:
--   1. `invoice_payments` — one row per payment against an invoice. Supports
--      partial payments and every payment method from "cash" to a processor
--      webhook row. A trigger keeps `invoices.status` + `invoices.paid_at` in
--      sync with `sum(invoice_payments.amount_cents)`, so manual record-payment
--      actions and processor webhooks both write to the same place with
--      identical downstream behaviour.
--   2. `integration_connections` — one row per (org, provider) OAuth link for
--      Stripe Connect, Square, and QuickBooks Online. Tokens are stored
--      encrypted at the application layer (AES-256-GCM via src/lib/crypto.ts)
--      so leaking the DB alone does not leak capability tokens.
--   3. `integration_events` — append-only log of inbound webhooks for
--      idempotency (dedupe on `event_id`) and debugging.
--   4. `invoices.number` — sequential human-readable invoice number per org
--      (e.g. INV-2026-0001) generated by a BEFORE INSERT trigger.
--   5. `invoices.public_token` — 16-char URL-safe capability token for the
--      public `/i/:token` no-login invoice view (same pattern as /claim/:token).
--   6. `clients.quickbooks_customer_id` — nullable cache of the QBO customer
--      id once a client has been mirrored into the user's QuickBooks ledger.
--   7. Audit log immutability — a trigger on `public.audit_log` that raises
--      on any UPDATE or DELETE. RLS already denies these at the app role
--      level, but this locks it down even for the service role, so no code
--      path (intentional or otherwise) can rewrite history.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_type where typname = 'payment_method') then
    create type public.payment_method as enum (
      'cash',
      'check',
      'bank_transfer',
      'zelle',
      'venmo',
      'cashapp',
      'card',
      'ach',
      'other'
    );
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'integration_provider') then
    create type public.integration_provider as enum (
      'stripe',
      'square',
      'quickbooks'
    );
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'integration_status') then
    create type public.integration_status as enum (
      'active',
      'disconnected',
      'error'
    );
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- Extend `invoices`
-- -----------------------------------------------------------------------------

alter table public.invoices
  add column if not exists number text,
  add column if not exists public_token text,
  add column if not exists voided_at timestamptz,
  add column if not exists payment_instructions text;

-- Unique per org so the admin's invoice list can use the number safely.
create unique index if not exists invoices_org_number_uidx
  on public.invoices (organization_id, number)
  where number is not null;

-- Public token must be globally unique — it's the entire capability.
create unique index if not exists invoices_public_token_uidx
  on public.invoices (public_token)
  where public_token is not null;

-- Bump the invoice_status enum to cover partial payments. Postgres can't
-- ALTER a type inside a transaction with other statements in Supabase's
-- migration runner, so we inline the ADD VALUE into its own DO block.
do $$
begin
  if not exists (
    select 1 from pg_enum
    where enumlabel = 'partially_paid'
      and enumtypid = 'public.invoice_status'::regtype
  ) then
    alter type public.invoice_status add value 'partially_paid' before 'paid';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_enum
    where enumlabel = 'void'
      and enumtypid = 'public.invoice_status'::regtype
  ) then
    alter type public.invoice_status add value 'void';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- Extend `clients`
-- -----------------------------------------------------------------------------

alter table public.clients
  add column if not exists quickbooks_customer_id text;

create index if not exists clients_quickbooks_customer_id_idx
  on public.clients (quickbooks_customer_id)
  where quickbooks_customer_id is not null;

-- -----------------------------------------------------------------------------
-- Table: invoice_payments
-- -----------------------------------------------------------------------------

create table if not exists public.invoice_payments (
  id                    uuid primary key default gen_random_uuid(),
  organization_id       uuid not null references public.organizations(id) on delete cascade,
  invoice_id            uuid not null references public.invoices(id) on delete cascade,
  amount_cents          integer not null check (amount_cents > 0),
  method                public.payment_method not null,
  reference             text,
  received_at           timestamptz not null default now(),
  recorded_by           uuid references public.memberships(id) on delete set null,
  notes                 text,
  -- Processor provenance. Populated when a webhook created this row; null
  -- for manual entries.
  provider              public.integration_provider,
  provider_payment_id   text,
  provider_fee_cents    integer,
  created_at            timestamptz not null default now()
);

create index if not exists invoice_payments_invoice_id_idx
  on public.invoice_payments (invoice_id);
create index if not exists invoice_payments_organization_id_idx
  on public.invoice_payments (organization_id);
create index if not exists invoice_payments_received_at_idx
  on public.invoice_payments (received_at desc);

-- Dedupe by processor payment id so a retried webhook can't double-count.
create unique index if not exists invoice_payments_provider_payment_uidx
  on public.invoice_payments (provider, provider_payment_id)
  where provider is not null and provider_payment_id is not null;

alter table public.invoice_payments enable row level security;
alter table public.invoice_payments force  row level security;

-- -----------------------------------------------------------------------------
-- Table: integration_connections
-- -----------------------------------------------------------------------------

create table if not exists public.integration_connections (
  id                      uuid primary key default gen_random_uuid(),
  organization_id         uuid not null references public.organizations(id) on delete cascade,
  provider                public.integration_provider not null,
  -- External account identifier (Stripe acct_xxx, Square merchant id, QBO realm id)
  external_account_id     text,
  external_account_label  text,
  -- ENCRYPTED blobs — AES-256-GCM via src/lib/crypto.ts. Never store raw tokens.
  access_token_ciphertext text,
  refresh_token_ciphertext text,
  token_expires_at        timestamptz,
  scope                   text,
  status                  public.integration_status not null default 'active',
  last_error              text,
  metadata                jsonb not null default '{}'::jsonb,
  connected_by            uuid references public.memberships(id) on delete set null,
  connected_at            timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- One active connection per (org, provider). Disconnected rows are kept for
-- history and can coexist because they don't match this partial index.
create unique index if not exists integration_connections_active_uidx
  on public.integration_connections (organization_id, provider)
  where status = 'active';

create index if not exists integration_connections_org_idx
  on public.integration_connections (organization_id);

drop trigger if exists integration_connections_set_updated_at
  on public.integration_connections;
create trigger integration_connections_set_updated_at
  before update on public.integration_connections
  for each row execute function public.set_updated_at();

alter table public.integration_connections enable row level security;
alter table public.integration_connections force  row level security;

-- -----------------------------------------------------------------------------
-- Table: integration_events
-- -----------------------------------------------------------------------------

create table if not exists public.integration_events (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,
  provider        public.integration_provider not null,
  event_id        text not null,
  event_type      text not null,
  payload         jsonb not null,
  processed_at    timestamptz,
  error           text,
  received_at     timestamptz not null default now()
);

-- Idempotency: one row per provider event id. Webhook handlers upsert on
-- this and short-circuit if `processed_at` is already set.
create unique index if not exists integration_events_provider_event_uidx
  on public.integration_events (provider, event_id);

create index if not exists integration_events_org_idx
  on public.integration_events (organization_id);
create index if not exists integration_events_received_at_idx
  on public.integration_events (received_at desc);

alter table public.integration_events enable row level security;
alter table public.integration_events force  row level security;

-- =============================================================================
-- Triggers
-- =============================================================================

-- Keep invoices.status + paid_at in sync with sum of invoice_payments.
-- A single function handles insert/update/delete on invoice_payments.
create or replace function public.sync_invoice_payment_totals()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invoice_id uuid;
  v_total      integer;
  v_paid       integer;
  v_status     public.invoice_status;
  v_paid_at    timestamptz;
  v_due_date   date;
  v_voided_at  timestamptz;
begin
  -- Figure out which invoice row this change touched.
  v_invoice_id := coalesce(new.invoice_id, old.invoice_id);
  if v_invoice_id is null then
    return coalesce(new, old);
  end if;

  select amount_cents, due_date, voided_at
    into v_total, v_due_date, v_voided_at
    from public.invoices
   where id = v_invoice_id;

  if not found then
    return coalesce(new, old);
  end if;

  select coalesce(sum(amount_cents), 0)
    into v_paid
    from public.invoice_payments
   where invoice_id = v_invoice_id;

  -- Void trumps everything.
  if v_voided_at is not null then
    v_status := 'void';
    v_paid_at := null;
  elsif v_paid >= v_total and v_total > 0 then
    v_status := 'paid';
    select max(received_at) into v_paid_at
      from public.invoice_payments
     where invoice_id = v_invoice_id;
  elsif v_paid > 0 then
    v_status := 'partially_paid';
    v_paid_at := null;
  else
    -- No payments. Fall back to sent / overdue / draft based on dates.
    if v_due_date is not null and v_due_date < current_date then
      v_status := 'overdue';
    else
      -- Leave status alone if it's already draft or sent so the admin's
      -- "send invoice" action controls the draft→sent transition. We only
      -- rewrite to overdue/paid/partially_paid/void from here.
      select status into v_status
        from public.invoices
       where id = v_invoice_id;
    end if;
    v_paid_at := null;
  end if;

  update public.invoices
     set status = v_status,
         paid_at = v_paid_at,
         updated_at = now()
   where id = v_invoice_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists invoice_payments_sync_totals on public.invoice_payments;
create trigger invoice_payments_sync_totals
  after insert or update or delete on public.invoice_payments
  for each row execute function public.sync_invoice_payment_totals();

-- ---- Invoice number generator -----------------------------------------------
-- Per-org sequential number, format INV-YYYY-NNNN. Allocated at INSERT time
-- inside a transaction so concurrent inserts can't collide. We look up the
-- current max for the org/year and add one; the unique index on
-- (organization_id, number) is the final race guard.
create or replace function public.assign_invoice_number()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_year int := extract(year from now())::int;
  v_prefix text := 'INV-' || v_year::text || '-';
  v_next int;
begin
  if new.number is not null and new.number <> '' then
    return new;
  end if;

  select coalesce(
           max(
             nullif(
               regexp_replace(number, '^' || v_prefix, ''),
               ''
             )::int
           ),
           0
         ) + 1
    into v_next
    from public.invoices
   where organization_id = new.organization_id
     and number like v_prefix || '%';

  new.number := v_prefix || lpad(v_next::text, 4, '0');
  return new;
end;
$$;

drop trigger if exists invoices_assign_number on public.invoices;
create trigger invoices_assign_number
  before insert on public.invoices
  for each row execute function public.assign_invoice_number();

-- ---- Public token generator -------------------------------------------------
create or replace function public.assign_invoice_public_token()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if new.public_token is null then
    -- 12 random bytes → 16 base64 chars (url-safe). pgcrypto.gen_random_bytes
    -- is available under extensions schema in Supabase.
    new.public_token := replace(
      replace(
        replace(
          encode(extensions.gen_random_bytes(12), 'base64'),
          '+', '-'
        ),
        '/', '_'
      ),
      '=', ''
    );
  end if;
  return new;
end;
$$;

drop trigger if exists invoices_assign_public_token on public.invoices;
create trigger invoices_assign_public_token
  before insert on public.invoices
  for each row execute function public.assign_invoice_public_token();

-- Backfill tokens + numbers for any invoices that predate this migration.
do $$
declare
  r record;
  v_prefix text;
  v_next int;
  v_token text;
begin
  for r in
    select id, organization_id, created_at, number, public_token
      from public.invoices
     where number is null or public_token is null
     order by organization_id, created_at
  loop
    if r.number is null then
      v_prefix := 'INV-' || extract(year from r.created_at)::int::text || '-';
      select coalesce(
               max(
                 nullif(regexp_replace(number, '^' || v_prefix, ''), '')::int
               ),
               0
             ) + 1
        into v_next
        from public.invoices
       where organization_id = r.organization_id
         and number like v_prefix || '%';
      update public.invoices
         set number = v_prefix || lpad(v_next::text, 4, '0')
       where id = r.id;
    end if;

    if r.public_token is null then
      v_token := replace(
        replace(
          replace(
            encode(extensions.gen_random_bytes(12), 'base64'),
            '+', '-'
          ),
          '/', '_'
        ),
        '=', ''
      );
      update public.invoices
         set public_token = v_token
       where id = r.id;
    end if;
  end loop;
end $$;

-- ---- Audit log immutability -------------------------------------------------
-- RLS already denies update/delete at the authenticated role level, but
-- a service-role-powered code path (or a buggy migration) could still
-- rewrite history. This trigger closes that loophole.
create or replace function public.audit_log_reject_mutations()
returns trigger
language plpgsql
as $$
begin
  raise exception 'audit_log is append-only (attempted %)', tg_op
    using errcode = 'insufficient_privilege';
end;
$$;

drop trigger if exists audit_log_block_update on public.audit_log;
create trigger audit_log_block_update
  before update on public.audit_log
  for each row execute function public.audit_log_reject_mutations();

drop trigger if exists audit_log_block_delete on public.audit_log;
create trigger audit_log_block_delete
  before delete on public.audit_log
  for each row execute function public.audit_log_reject_mutations();

-- =============================================================================
-- RLS policies — admin-only read/write across the three new tables
-- =============================================================================

-- ---- invoice_payments -------------------------------------------------------

drop policy if exists "admins read invoice_payments" on public.invoice_payments;
create policy "admins read invoice_payments"
on public.invoice_payments for select
to authenticated
using (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]));

drop policy if exists "admins insert invoice_payments" on public.invoice_payments;
create policy "admins insert invoice_payments"
on public.invoice_payments for insert
to authenticated
with check (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]));

drop policy if exists "admins update invoice_payments" on public.invoice_payments;
create policy "admins update invoice_payments"
on public.invoice_payments for update
to authenticated
using (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]))
with check (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]));

drop policy if exists "admins delete invoice_payments" on public.invoice_payments;
create policy "admins delete invoice_payments"
on public.invoice_payments for delete
to authenticated
using (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]));

-- ---- integration_connections ------------------------------------------------

drop policy if exists "admins read integration_connections" on public.integration_connections;
create policy "admins read integration_connections"
on public.integration_connections for select
to authenticated
using (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]));

drop policy if exists "admins insert integration_connections" on public.integration_connections;
create policy "admins insert integration_connections"
on public.integration_connections for insert
to authenticated
with check (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]));

drop policy if exists "admins update integration_connections" on public.integration_connections;
create policy "admins update integration_connections"
on public.integration_connections for update
to authenticated
using (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]))
with check (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]));

drop policy if exists "admins delete integration_connections" on public.integration_connections;
create policy "admins delete integration_connections"
on public.integration_connections for delete
to authenticated
using (public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[]));

-- ---- integration_events -----------------------------------------------------
-- Webhooks are written by the service-role client (bypassing RLS). Admins
-- get read access so the settings page can show a dispatch log.

drop policy if exists "admins read integration_events" on public.integration_events;
create policy "admins read integration_events"
on public.integration_events for select
to authenticated
using (
  organization_id is null
  or public.current_user_has_role(organization_id, array['owner','admin']::public.membership_role[])
);

-- -----------------------------------------------------------------------------
-- Comments
-- -----------------------------------------------------------------------------

comment on table public.invoice_payments is
  'One row per payment against an invoice. Manual entries and processor webhooks write here with the same shape; a trigger syncs invoices.status.';

comment on table public.integration_connections is
  'Per-org OAuth linkage to Stripe/Square/QuickBooks. Tokens are AES-256-GCM encrypted at the application layer (src/lib/crypto.ts).';

comment on table public.integration_events is
  'Append-only log of inbound webhooks for idempotency (dedupe on provider+event_id) and debugging.';

comment on column public.invoices.number is
  'Sequential human-readable invoice number per org (e.g. INV-2026-0001), assigned by trigger on insert.';

comment on column public.invoices.public_token is
  'URL-safe capability token for the public /i/:token no-login view. Generated by trigger on insert.';

comment on column public.invoices.payment_instructions is
  'Free-form per-invoice payment instructions shown on the public view (Zelle, mailing address, wire info). Overrides the org-wide default in settings.';

comment on column public.clients.quickbooks_customer_id is
  'Cached QBO customer id once this client has been mirrored into the orgs QuickBooks ledger.';
